##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: retries-dlq-strategy
  devtools:
    add-properties: false
  rabbitmq:
    host: 34.194.141.33
    port: 5672
    username: <PUT_THE_USER>
    password: <PUT_THE_PASSWORD>

app:
  async:
    withDLQRetry: true
    retryDelay: 5000
    maxRetries: 3


